---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-rs0-1
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-server|nfs-ip
    path: "/mongodb-volume-name"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-data-rs0-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-rs01
  labels:
    app: myapp
    databaseVendor: mongo
    instanceType: dev
spec:
  type: LoadBalancer
  ports:
  - name: mongo-port
    port: 27017
    targetPort: 27017
    nodePort: 30017
    protocol: TCP
  selector:
    app: myapp
    databaseVendor: mongo
    instanceType: dev
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: dev-mongo-rc1
  labels:
    name: dev-mongo-rc1
spec:
  replicas: 1
  selector:
    app: myapp
    databaseVendor: mongo
    instanceType: dev
  template:
    metadata:
      labels:
        app: myapp
        databaseVendor: mongo
        instanceType: dev
        name: dev-mongo
        instance: dev-mongo
    spec:
      volumes:
      - name: mongodb-data-rs0-1
        persistentVolumeClaim:
          claimName: mongodb-data-rs0-1
      containers:
      - name: dev-mongo-rc1
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data-rs0-1
          mountPath: /data/db
