apiVersion: v1
kind: Pod
metadata:
  name: my-gpu-pod
spec:
  containers:
  - name: vision-api-service
    image: gcr.io/base-gcs-test/vision-api:v1
    command: ["/bin/bash", "-c","tail -f /dev/null"]
    resources:
      limits:
       nvidia.com/gpu: 1

---

apiVersion: v1
kind: Service
metadata:
  name: vision-api-service
  labels:
    app: vision-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000      # push by ConfigMap
      targetPort: 3000
      protocol: TCP
  externalTrafficPolicy: Local
  selector:
    app: vision-api-service

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vision-api-service
spec:
  serviceName: vision-api-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
apiVersion: v1
      app: vision-api-service
  template:
    metadata:
      labels:
        app: vision-api-service
    spec:
      containers:
      - name: vision-api-service
        image: gcr.io/base-gcs-test/vision-api:v1
        ports:
        - containerPort: 3000
          name: api